/* This file is automatically generated by gensymlist.sh. DO NOT EDIT! */
/*
 *  holy  --  GRand Unified Bootloader
 *  Copyright (C) 2002,2006,2007,2008,2009,2010  Free Software Foundation, Inc.
 *
 *  holy is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  holy is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with holy.  If not, see <http://www.gnu.org/licenses/>.
 */

#include <../config.h>
#include <../include/holy/cache.h>
#include <../include/holy/command.h>
#include <../include/holy/device.h>
#include <../include/holy/disk.h>
#include <../include/holy/dl.h>
#include <../include/holy/env.h>
#include <../include/holy/env_private.h>
#include <../include/holy/err.h>
#include <../include/holy/file.h>
#include <../include/holy/fs.h>
#include <../include/holy/i18n.h>
#include <../include/holy/kernel.h>
#include <../include/holy/list.h>
#include <../include/holy/misc.h>
#include <../include/holy/compiler-rt.h>
#include <../include/holy/mm.h>
#include <../include/holy/parser.h>
#include <../include/holy/partition.h>
#include <../include/holy/term.h>
#include <../include/holy/time.h>
#include <../include/holy/mm_private.h>
#include <../include/holy/net.h>
#include <../include/holy/tpm.h>
#include <../include/holy/memory.h>
#include <../include/holy/machine/kernel.h>
#include <../include/holy/machine/pxe.h>
#include <../include/holy/machine/int.h>
#include <../include/holy/i386/tsc.h>

#define COMPILE_TIME_ASSERT(cond) switch (0) { case 1: case !(cond): ; }

#pragma GCC diagnostic ignored "-Wmissing-format-attribute"

void
holy_register_exported_symbols (void)
{
  struct symtab { const char *name; void *addr; int isfunc; };
  struct symtab *p;
  static struct symtab tab[] =
    {
      {"holy_bios_interrupt", holy_bios_interrupt, 1},
      {"holy_boot_device", (void *) &holy_boot_device, 0},
      {"holy_command_list", (void *) &holy_command_list, 0},
      {"holy_current_context", (void *) &holy_current_context, 0},
      {"holy_device_close", holy_device_close, 1},
      {"holy_device_iterate", holy_device_iterate, 1},
      {"holy_device_open", holy_device_open, 1},
      {"holy_disk_cache_table", (void *) &holy_disk_cache_table, 0},
      {"holy_disk_close", holy_disk_close, 1},
      {"holy_disk_dev_list", (void *) &holy_disk_dev_list, 0},
      {"holy_disk_dev_register", holy_disk_dev_register, 1},
      {"holy_disk_dev_unregister", holy_disk_dev_unregister, 1},
      {"holy_disk_firmware_fini", (void *) &holy_disk_firmware_fini, 0},
      {"holy_disk_firmware_is_tainted", (void *) &holy_disk_firmware_is_tainted, 0},
      {"holy_disk_get_size", holy_disk_get_size, 1},
      {"holy_disk_open", holy_disk_open, 1},
      {"holy_disk_read", holy_disk_read, 1},
      {"holy_disk_write_weak", (void *) &holy_disk_write_weak, 0},
      {"holy_divmod64", holy_divmod64, 1},
      {"holy_dl_head", (void *) &holy_dl_head, 0},
      {"holy_dl_load", holy_dl_load, 1},
      {"holy_dl_load_core_noinit", holy_dl_load_core_noinit, 1},
      {"holy_dl_ref", holy_dl_ref, 1},
      {"holy_dl_unload", holy_dl_unload, 1},
      {"holy_dl_unref", holy_dl_unref, 1},
      {"holy_env_export", holy_env_export, 1},
      {"holy_env_get", holy_env_get, 1},
      {"holy_env_set", holy_env_set, 1},
      {"holy_env_unset", holy_env_unset, 1},
      {"holy_env_update_get_sorted", holy_env_update_get_sorted, 1},
      {"holy_err_printed_errors", (void *) &holy_err_printed_errors, 0},
      {"holy_errmsg", (void *) &holy_errmsg, 0},
      {"holy_errno", (void *) &holy_errno, 0},
      {"holy_error", holy_error, 1},
      {"holy_error_pop", holy_error_pop, 1},
      {"holy_error_push", holy_error_push, 1},
      {"holy_exit", holy_exit, 1},
      {"holy_fatal", holy_fatal, 1},
      {"holy_file_close", holy_file_close, 1},
      {"holy_file_filters_all", (void *) &holy_file_filters_all, 0},
      {"holy_file_filters_enabled", (void *) &holy_file_filters_enabled, 0},
      {"holy_file_get_device_name", holy_file_get_device_name, 1},
      {"holy_file_open", holy_file_open, 1},
      {"holy_file_progress_hook", (void *) &holy_file_progress_hook, 0},
      {"holy_file_read", holy_file_read, 1},
      {"holy_file_seek", holy_file_seek, 1},
      {"holy_free", holy_free, 1},
      {"holy_fs_autoload_hook", (void *) &holy_fs_autoload_hook, 0},
      {"holy_fs_list", (void *) &holy_fs_list, 0},
      {"holy_fs_probe", holy_fs_probe, 1},
      {"holy_get_time_ms", holy_get_time_ms, 1},
      {"holy_getkey", holy_getkey, 1},
      {"holy_getkey_noblock", holy_getkey_noblock, 1},
      {"holy_gettext", (void *) &holy_gettext, 0},
      {"holy_isspace", holy_isspace, 1},
      {"holy_list_push", holy_list_push, 1},
      {"holy_list_remove", holy_list_remove, 1},
      {"holy_machine_fini", holy_machine_fini, 1},
      {"holy_machine_mmap_iterate", holy_machine_mmap_iterate, 1},
      {"holy_malloc", holy_malloc, 1},
      {"holy_memalign", holy_memalign, 1},
      {"holy_memcmp", holy_memcmp, 1},
      {"holy_memmove", holy_memmove, 1},
      {"holy_memset", holy_memset, 1},
      {"holy_millisleep", holy_millisleep, 1},
      {"holy_mm_base", (void *) &holy_mm_base, 0},
      {"holy_modbase", (void *) &holy_modbase, 0},
      {"holy_named_list_find", holy_named_list_find, 1},
      {"holy_net_open", (void *) &holy_net_open, 0},
      {"holy_net_poll_cards_idle", (void *) &holy_net_poll_cards_idle, 0},
      {"holy_parser_cmdline_state", holy_parser_cmdline_state, 1},
      {"holy_parser_split_cmdline", holy_parser_split_cmdline, 1},
      {"holy_partition_get_name", holy_partition_get_name, 1},
      {"holy_partition_iterate", holy_partition_iterate, 1},
      {"holy_partition_map_list", (void *) &holy_partition_map_list, 0},
      {"holy_partition_probe", holy_partition_probe, 1},
      {"holy_pc_net_config", (void *) &holy_pc_net_config, 0},
      {"holy_print_error", holy_print_error, 1},
      {"holy_printf", holy_printf, 1},
      {"holy_printf_", holy_printf_, 1},
      {"holy_puts_", holy_puts_, 1},
      {"holy_pxe_call", holy_pxe_call, 1},
      {"holy_real_dprintf", holy_real_dprintf, 1},
      {"holy_realidt", (void *) &holy_realidt, 0},
      {"holy_realloc", holy_realloc, 1},
      {"holy_refresh", holy_refresh, 1},
      {"holy_register_command_prio", holy_register_command_prio, 1},
      {"holy_register_variable_hook", holy_register_variable_hook, 1},
      {"holy_snprintf", holy_snprintf, 1},
      {"holy_strchr", holy_strchr, 1},
      {"holy_strcmp", holy_strcmp, 1},
      {"holy_strcpy", holy_strcpy, 1},
      {"holy_strdup", holy_strdup, 1},
      {"holy_strlen", holy_strlen, 1},
      {"holy_strncmp", holy_strncmp, 1},
      {"holy_strndup", holy_strndup, 1},
      {"holy_strrchr", holy_strrchr, 1},
      {"holy_strtoul", holy_strtoul, 1},
      {"holy_strtoull", holy_strtoull, 1},
      {"holy_strword", holy_strword, 1},
      {"holy_term_highlight_color", (void *) &holy_term_highlight_color, 0},
      {"holy_term_inputs", (void *) &holy_term_inputs, 0},
      {"holy_term_inputs_disabled", (void *) &holy_term_inputs_disabled, 0},
      {"holy_term_normal_color", (void *) &holy_term_normal_color, 0},
      {"holy_term_outputs", (void *) &holy_term_outputs, 0},
      {"holy_term_outputs_disabled", (void *) &holy_term_outputs_disabled, 0},
      {"holy_term_poll_usb", (void *) &holy_term_poll_usb, 0},
      {"holy_tpm_measure", holy_tpm_measure, 1},
      {"holy_tsc_rate", (void *) &holy_tsc_rate, 0},
      {"holy_unregister_command", holy_unregister_command, 1},
      {"holy_vprintf", holy_vprintf, 1},
      {"holy_vsnprintf", holy_vsnprintf, 1},
      {"holy_xasprintf", holy_xasprintf, 1},
      {"holy_xputs", (void *) &holy_xputs, 0},
      {"holy_xvasprintf", holy_xvasprintf, 1},
      {"holy_zalloc", holy_zalloc, 1},
      {"memcmp", memcmp, 1},
      {"memcpy", memcpy, 1},
      {"memmove", memmove, 1},
      {"memset", memset, 1},
      {0, 0, 0}
    };

  COMPILE_TIME_ASSERT (sizeof (tab) > sizeof (tab[0]));
  for (p = tab; p->name; p++)
    holy_dl_register_symbol (p->name, p->addr, p->isfunc, 0);
}
