#! /bin/sh
#
#
#
#
#
#
#
#
cat <<EOF
/* This file is automatically generated by geninit.sh. DO NOT EDIT! */
/*
 *
 */

#include <holy/emu/misc.h>

EOF

for mod in "$@"; do
    echo "extern void holy_${mod}_init (void);"
    echo "extern void holy_${mod}_fini (void);"
done

cat <<EOF
void
holy_init_all (void)
{
EOF

for mod in "$@"; do
    echo "holy_${mod}_init ();"
done

cat <<EOF
}
EOF

cat <<EOF
void
holy_fini_all (void)
{
EOF

for mod in "$@"; do
    echo "holy_${mod}_fini ();"
done

cat <<EOF
}
EOF
